name: Release

on:
  push:
    branches: 
      - 'feature/**'
      - main

jobs:
  # This workflow contains a single job called "release"
  release:
    name: Build & Deploy to Cloud run
    environment: dev
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with: 
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.SERVICE_ACCOUNT }}

    - name: Create Environment Variables
      run: |
        export PACKAGE_VERSION=0.1.0
        export PACKAGE_NAME=$(basename $GITHUB_REPOSITORY)
        echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build . -t eu.gcr.io/${{ secrets.GCP_PID }}/${{env.PACKAGE_NAME}}:${{env.PACKAGE_VERSION}}
 
    - name: Push Docker image to Dockerhub 
      run: |
        docker push eu.gcr.io/${{ secrets.GCP_PID }}/${{env.PACKAGE_NAME}}:${{env.PACKAGE_VERSION}}
    
    - name: Setup GCloud 
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PID }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
        export_default_credentials: true
    
    - name: Deploy image
      run: | 
        gcloud run deploy ${{env.PACKAGE_NAME}} --set-env-vars "GCP_PID=${{ secrets.GCP_PID }}" --service-account=${{ secrets.MICROSERVICE_ACCOUNT }} --project=${{ secrets.GCP_PID }} --image=eu.gcr.io/${{ secrets.GCP_PID }}/${{env.PACKAGE_NAME}}:${{env.PACKAGE_VERSION}} --platform=managed --region=europe-west1 --allow-unauthenticated 